### PR TITLE
Update README by adding export bookmarks feature

### LINKED ISSUE #74: Update README.rst
- Resize the image
- Fast forward the video
- I got WARNING while performing `rst2html README.rst output.html`
```
README.rst:174: (WARNING/2) Title underline too short.

`Licence <https://github.com/projectreadit/readit/blob/master/LICENSE>`_
***********************************************************************
README.rst:174: (WARNING/2) Title underline too short.

`Licence <https://github.com/projectreadit/readit/blob/master/LICENSE>`_
```

### PR DESCRIPTION
**Pull request by shitalmule04**
Fix #74 

New feature i.e. **Export Bookmarks** is introduced, so did changes into the `README` under following sections:

- Features
- Examples
- Command line options

Some other changes are:

- Added badge for documentation

- Provide solution for the image resize

### CODE REVIEW

**Comment by ganeshhubale** [comment]
@shitalmule04 
Please update README with the new feature.

**Comment by shitalmule04** [comment]
@ganeshhubale, Can you merge this PR? All updates regarding **Export** is done.

**Comment by ganeshhubale** [comment]
@shitalmule04 
- ok

**Comment by ganeshhubale** [comment]
@shitalmule04 
- New feature 
    - Bookmark URLs either online or offline

**Pull request merged**
