### PR TITLE
Release job

### PR DESCRIPTION
**Pull request by digitronik**
- added auto release workflow
- added setup.cfg for metadata

### CODE REVIEW

**Comment by ganeshhubale** [comment]
@digitronik Thanks for this PR. 
- Tested this locally but getting below error after installation with setup.py
```
(new_env) [ghubale@localhost readit]$ readit
Traceback (most recent call last):
  File "/home/ghubale/projectreadit/new_env/bin/readit", line 11, in <module>
    load_entry_point('readit==0.0.0', 'console_scripts', 'readit')()
  File "/home/ghubale/projectreadit/new_env/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/ghubale/projectreadit/new_env/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/home/ghubale/projectreadit/new_env/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/home/ghubale/projectreadit/new_env/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'readit'
(new_env) [ghubale@localhost readit]$ 
```
Please have a look :)

**Comment by digitronik** [comment]
let me check :+1:

**Comment by digitronik** [comment]
@ganeshhubale can you check locally now. we wont have tests :) so we need to check locally this behavior.

**Comment by ganeshhubale** [comment]
Looks good to me. Works as expected :)

**Pull request merged**
